version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/rogierlommers/logrus-redis-hook
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go get github.com/mattn/goveralls
      - run: go test -v ./...
      - run: go test -cover -race -coverprofile=coverage.out
      - run: go tool cover -func=coverage.out
      - run: ls /go/bin
      - run: /go/bin/goveralls -coverprofile=coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
